### ISSUE TITLE
Display not working

### ISSUE THREAD

**Issue by surajkadapa** [acmpesuecc/7_seg_display#1]
The IC is not able to display the numbers and there is no counter to count through the numbers, make sure the 7-segment display displays all the numbers from 0 through 9.

**Comment by vicks6969** [comment]
assign me please

**Comment by surajkadapa** [comment]
Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by ManushriJ** [comment]
can i get assigned

**Comment by ProSai8055** [comment]
can i been assigned

**Comment by surajkadapa** [comment]
@vicks6969 i'm reassigning because time is out.

**Comment by surajkadapa** [comment]
@ProSai8055 Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by KunalMaverick** [comment]
is this assigned?
or open??

**Comment by Alley2717** [comment]
can i try

**Comment by surajkadapa** [comment]
@KunalMaverick Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by ssether04** [comment]
can i get assigned if this is still open?

**Comment by IshaanNene** [comment]
assign me this issue

**Comment by surajkadapa** [comment]
@IshaanNene Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by surajkadapa** [comment]
This issue has been solved.
